In [61]:
import MDAnalysis as mda
import numpy as np

## Gromacs TRR files

Read completely to memory

In [38]:
u = mda.Universe('../trajectories/traj.trr', in_memory=True)

This reads in the complete trajectory. We can get individual slices from the trajectory as required

In [39]:
u.trajectory

<MemoryReader with 101 frames of 216 atoms>

The above object contains snapshots along the trajectory

Get the box size

In [40]:
u.trajectory[0].dimensions

array([20.755402, 20.755402, 20.755402, 90.      , 90.      , 90.      ],
      dtype=float32)

Get positions of atoms

In [41]:
u.trajectory[0].positions[0]

array([17.51    ,  1.      , 14.370001], dtype=float32)

Get the velocities

In [42]:
u.trajectory[0].velocities[0]

array([ 1.4620138,  1.9999537, -1.1139722], dtype=float32)

Read without storing in memory

In [43]:
u = mda.Universe('../trajectories/traj.trr')

In [44]:
u.trajectory[0].dimensions

array([20.755402, 20.755402, 20.755402, 90.      , 90.      , 90.      ],
      dtype=float32)

In [45]:
u.trajectory[0].positions[0]

array([17.51    ,  1.      , 14.370001], dtype=float32)

Write trajectory to file

In [47]:
atoms = u.select_atoms("all")
with mda.Writer("atoms.trr", atoms.n_atoms) as W:
    for ts in u.trajectory:
        W.write(atoms)

Slice trajectory

In [48]:
sliced = u.trajectory[10:20]

In [49]:
sliced.trajectory

<TRRReader ../trajectories/traj.trr with 101 frames of 216 atoms>

Write the sliced part

In [50]:
atoms = u.select_atoms("all")
with mda.Writer("atoms_sliced.trr", atoms.n_atoms) as W:
    for ts in u.trajectory[10:20]:
        W.write(atoms)

Check the number of frames

In [55]:
u = mda.Universe('atoms_sliced.trr', in_memory=True)

In [56]:
u.trajectory

<MemoryReader with 10 frames of 216 atoms>

Modify contents

In [59]:
u.trajectory[0].velocities.shape

(216, 3)

For testing lets set to 0

In [62]:
new_vels = np.zeros((216, 3))

In [63]:
u.trajectory[0].velocities = new_vels

Write out

In [64]:
atoms = u.select_atoms("all")
with mda.Writer("atoms_reset.trr", atoms.n_atoms) as W:
    for ts in u.trajectory:
        W.write(atoms)

Read in and check

In [65]:
u = mda.Universe('atoms_reset.trr', in_memory=True)

In [66]:
u.trajectory

<MemoryReader with 10 frames of 216 atoms>

In [67]:
u.trajectory[0].velocities

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0